"""Initial schema

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create request_logs table
    op.create_table('request_logs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('fingerprint_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of request fingerprint'),
        sa.Column('ip_address', postgresql.INET(), nullable=False, comment='Client IP address'),
        sa.Column('user_agent', sa.Text(), nullable=True, comment='User-Agent string'),
        sa.Column('endpoint', sa.String(length=255), nullable=False, comment='API endpoint path'),
        sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP method'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='Request status: allowed, blocked, whitelisted'),
        sa.Column('risk_score', sa.Integer(), nullable=False, default=0, comment='Calculated risk score (0-100)'),
        sa.Column('block_reason', sa.String(length=255), nullable=True, comment='Reason for blocking if applicable'),
        sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='Response time in milliseconds'),
        sa.PrimaryKeyConstraint('id'),
        comment='Request logs for tracking all incoming requests'
    )
    
    # Create indexes for request_logs
    op.create_index('idx_request_logs_fingerprint', 'request_logs', ['fingerprint_hash'], unique=False)
    op.create_index('idx_request_logs_ip', 'request_logs', ['ip_address'], unique=False)
    op.create_index('idx_request_logs_created_at', 'request_logs', ['created_at'], unique=False)
    op.create_index('idx_request_logs_status', 'request_logs', ['status'], unique=False)
    op.create_index('idx_request_logs_endpoint', 'request_logs', ['endpoint'], unique=False)
    op.create_index('idx_request_logs_composite', 'request_logs', ['ip_address', 'created_at'], unique=False)
    
    # Create blacklist table
    op.create_table('blacklist',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('ip_address', postgresql.INET(), nullable=False, unique=True, comment='Blocked IP address'),
        sa.Column('reason', sa.String(length=500), nullable=False, comment='Reason for blocking'),
        sa.Column('blocked_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='When the IP was blocked'),
        sa.Column('expires_at', postgresql.TIMESTAMPTZ(timezone=True), nullable=True, comment='When the block expires (NULL = permanent)'),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True, server_default='true', comment='Whether the block is currently active'),
        sa.Column('created_by', sa.String(length=100), nullable=False, default='system', server_default='system', comment='Who created the block (system or admin)'),
        sa.PrimaryKeyConstraint('id'),
        comment='IP blacklist entries'
    )
    
    # Create indexes for blacklist
    op.create_index('idx_blacklist_active', 'blacklist', ['ip_address'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('idx_blacklist_expires', 'blacklist', ['expires_at'], unique=False)
    op.create_index('idx_blacklist_created_at', 'blacklist', ['blocked_at'], unique=False)
    
    # Create whitelist table
    op.create_table('whitelist',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('ip_address', postgresql.INET(), nullable=False, unique=True, comment='Whitelisted IP address'),
        sa.Column('note', sa.String(length=500), nullable=True, comment='Notes about why this IP is whitelisted'),
        sa.Column('added_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='When the IP was added to whitelist'),
        sa.Column('added_by', sa.String(length=100), nullable=False, default='system', server_default='system', comment='Who added the IP (system or admin)'),
        sa.PrimaryKeyConstraint('id'),
        comment='IP whitelist entries'
    )
    
    # Create indexes for whitelist
    op.create_index('idx_whitelist_ip', 'whitelist', ['ip_address'], unique=False)
    op.create_index('idx_whitelist_added_at', 'whitelist', ['added_at'], unique=False)
    
    # Create endpoint_configs table
    op.create_table('endpoint_configs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('endpoint_pattern', sa.String(length=255), nullable=False, unique=True, comment='Endpoint pattern (supports wildcards)'),
        sa.Column('rate_limit', sa.Integer(), nullable=False, default=100, comment='Maximum requests per window'),
        sa.Column('window_seconds', sa.Integer(), nullable=False, default=60, comment='Time window in seconds'),
        sa.Column('score_threshold', sa.Integer(), nullable=False, default=50, comment='Risk score threshold for blocking'),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=True, server_default='true', comment='Whether this configuration is active'),
        sa.PrimaryKeyConstraint('id'),
        comment='Endpoint-specific rate limiting configurations'
    )
    
    # Create indexes for endpoint_configs
    op.create_index('idx_endpoint_configs_pattern', 'endpoint_configs', ['endpoint_pattern'], unique=False)
    op.create_index('idx_endpoint_configs_active', 'endpoint_configs', ['is_active'], unique=False)
    
    # Create blocked_events table
    op.create_table('blocked_events',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('ip_address', postgresql.INET(), nullable=False, comment='Blocked IP address'),
        sa.Column('fingerprint_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of request fingerprint'),
        sa.Column('endpoint', sa.String(length=255), nullable=False, comment='API endpoint that was blocked'),
        sa.Column('risk_score', sa.Integer(), nullable=False, comment='Risk score at time of blocking'),
        sa.Column('block_reasons', postgresql.ARRAY(sa.Text()), nullable=False, comment='Array of reasons for blocking'),
        sa.Column('blocked_at', postgresql.TIMESTAMPTZ(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='When the block occurred'),
        sa.Column('unblocked_at', postgresql.TIMESTAMPTZ(timezone=True), nullable=True, comment='When the block was lifted'),
        sa.Column('auto_unblocked', sa.Boolean(), nullable=False, default=False, server_default='false', comment='Whether unblocking was automatic'),
        sa.PrimaryKeyConstraint('id'),
        comment='Blocked events for audit trail'
    )
    
    # Create indexes for blocked_events
    op.create_index('idx_blocked_events_ip', 'blocked_events', ['ip_address'], unique=False)
    op.create_index('idx_blocked_events_blocked_at', 'blocked_events', ['blocked_at'], unique=False)
    op.create_index('idx_blocked_events_fingerprint', 'blocked_events', ['fingerprint_hash'], unique=False)
    op.create_index('idx_blocked_events_endpoint', 'blocked_events', ['endpoint'], unique=False)
    op.create_index('idx_blocked_events_composite', 'blocked_events', ['ip_address', 'blocked_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_blocked_events_composite', table_name='blocked_events')
    op.drop_index('idx_blocked_events_endpoint', table_name='blocked_events')
    op.drop_index('idx_blocked_events_fingerprint', table_name='blocked_events')
    op.drop_index('idx_blocked_events_blocked_at', table_name='blocked_events')
    op.drop_index('idx_blocked_events_ip', table_name='blocked_events')
    op.drop_table('blocked_events')
    op.drop_index('idx_endpoint_configs_active', table_name='endpoint_configs')
    op.drop_index('idx_endpoint_configs_pattern', table_name='endpoint_configs')
    op.drop_table('endpoint_configs')
    op.drop_index('idx_whitelist_added_at', table_name='whitelist')
    op.drop_index('idx_whitelist_ip', table_name='whitelist')
    op.drop_table('whitelist')
    op.drop_index('idx_blacklist_created_at', table_name='blacklist')
    op.drop_index('idx_blacklist_expires', table_name='blacklist')
    op.drop_index('idx_blacklist_active', table_name='blacklist')
    op.drop_table('blacklist')
    op.drop_index('idx_request_logs_composite', table_name='request_logs')
    op.drop_index('idx_request_logs_endpoint', table_name='request_logs')
    op.drop_index('idx_request_logs_status', table_name='request_logs')
    op.drop_index('idx_request_logs_created_at', table_name='request_logs')
    op.drop_index('idx_request_logs_ip', table_name='request_logs')
    op.drop_index('idx_request_logs_fingerprint', table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
